apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akhil27051999/argocd-gitops-demo-project
    targetRevision: main
    path: manifests-flask/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

